---
- name: Automate SNOW - Incident Closed
  hosts: localhost
  connection: local
  vars:
    sn_close_code: "Solved (Work Around)"
    sn_close_notes: "This incident has been resolved through automated means via EDA Ansible, Job ID: https://192.168.100.111/#/jobs/playbook/{{ ac_job_id | default('0') }}/output. As a result, the ticket will now be marked as closed."
    sn_incident_number: "{{ sn_incident_number | default('0') }}"
#  vars_files:
#    - vars/main.yml
  collections:
    - servicenow.itsm

  tasks:
    # Always give your tasks a useful name
      # This task leverages the 'incident' module from the 'itsm' collection 
      # within the 'servicenow' namespace
    - name: Closed incident
      servicenow.itsm.incident:
        instance:
          host: "{{ snow_instance }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        state: closed
        close_code: "{{ sn_close_code }}"
        close_notes: "{{ sn_close_notes }}"
        number: "{{ sn_incident_number }}"
        other:
          work_notes: "{{ sn_close_notes }}"


    - name: Self-Healing details
      debug:
        msg: "https://192.168.100.111/#/jobs/playbook/{{ ac_job_id | default('0') }}/output"
