---
- name: Execute one or more TSO commands.
  hosts: zos_host
  gather_facts: false
  vars:
    zos_tso_command: |
      LISTCAT ENT('SYS1.PARMLIB') ALL
      LISTUSER IBMUSER
  tasks:

    - name: Execute the command(s) and return output.
      block:
        - name: Run z/OS TSO command(s).
          ibm.ibm_zos_core.zos_tso_command:
            commands: "{{ zos_tso_command.split('\n') | default('NOP') }}"
          register: command

      always:
        - name: Print results from command(s).
          ansible.builtin.debug:
            var: command.output

