download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/ibm-ibm_zos_ims-1.3.0.tar.gz
format_version: 1.0.0
name: ibm_zos_ims
namespace: ibm
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.3.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/ibm/ibm_zos_ims/versions/1.3.0/
